### ISSUE TITLE
feat: run ZARP workflow

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#11]
**Describe the solution you'd like**

- Implement in `zarp.zarp.run_zarp()`
- Return Pandas `DataFrame` of samples from `zarp.zarp.process_samples()` (currently returns `None`) and pass into `zarp.zarp.run_zarp()`
- To write out the sample table, make use of `zarp.samples.sample_table_processor.write()`.
- To write out the config file, make use of `zarp.snakemake.config_file_processor.ConfigFileProcessor`
- To trigger the workflow, make use of `zarp.snakemake.run.SnakemakeExecutor`.

**Note:** Will fail if not all required metadata are available. To test, a complete ZARP sample table has to be provided.

**Comment by dominikburri** [comment]
See commit fc452fd78e681883545db96e9def7a96bb111ad9

**Comment by uniqueg** [comment]
Proper end-to-end testing would be blocked by #25 and #34, but if using a full sample table can already be implemented.
