### ISSUE TITLE
Integration of zarp

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/zarp-cli#18]
zarp-cli relies on [zarp](https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp), but it is not available yet.

**Describe the solution you'd like**
The most likely solution involves the cloning of zarp repo and making it available in this repo.

**Describe alternatives you've considered**
An alternative could be to include a particular, hardcoded version of zarp in this repo.

**Comment by uniqueg** [comment]
ZARP is now available

**Comment by dominikburri** [comment]
Do you mean with available that it is public? how to make it accessible in this repo?
