### ISSUE TITLE
Clone repos from github

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/zarp-cli#22]
**Is your feature request related to a problem? Please describe.**
External git repositories should be added to this one in order to work properly.

**Describe the solution you'd like**
Use [`GitPython` ](https://gitpython.readthedocs.io/en/stable/intro.html)in order to obtain github repos as submodules.

**Describe alternatives you've considered**
Manually clone the repo into a directory of choice.

**Additional context**

- [ ] Selection of commit or tag of cloned repo

**Comment by dominikburri** [comment]
See WIP branch `clone-repos` for updates, e.g. commit abae15d6175162990ef68da9c188fd2ce4a565ce.

**Comment by dominikburri** [comment]
I read more about submodules and I think the main idea is to have the repository (zarp-cli) with the submodules fixed and annotated. It is not really intended to do this during runtime. I mean adding a submodule changes the git index and creates a `.gitmodules`. 

Given that we simply want to use the external repos as dependencies and not really modify them, we should probably deal with this with something like [maven](https://maven.apache.org/), but this is for java. 
The python alternative seems to be [setuptools](https://pypi.org/project/setuptools/), which we are already using in `setup.py`. 
So can we not simply add github and software dependencies in `setup.py`? @uniqueg 

Maybe like described [here](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#dependencies-that-aren-t-in-pypi)?

**Comment by AngryMaciek** [comment]
If you put out a tagged release of the dependency you can just `wget` it here (even during runtime), right? But maybe I misunderstood you, thats just a loose suggestion...

**Comment by dominikburri** [comment]
yeah I guess that you basically do this with `setuptools`. Because you also need to manage the other dependencies. Also, how to make sure things are running when only downloading some files? As I understand it, this is the point of deployment systems.

But given that we want to incorporate repos that are Snakemake workflows, we maybe simply want to use Snakemake's functionalites? Like subworkflows? 

I'm not sure on how to best integrate a python module (which this is going to be) with Snakemake workflows. 
Maybe I'm raising too many questions and things are already handled. But I want to be sure that using git's `submodules` is the way to go.

**Comment by AngryMaciek** [comment]
> But given that we want to incorporate repos that are Snakemake workflows, we maybe simply want to use Snakemake's functionalites? Like subworkflows?

I don't think this will work, subworkflows are triggered by a "main" snakemake workflow, i.e. they require _snakemake_ program to be running to interpret subworkflows.  

Here we have just a Python module (command line app) that would trigger workflows (as new snakemake commands). There is no "main" Snakemake workflow running at the level of user commands yet. Maybe you could encapsulate all the CLI into a "mock" workflow just to have one, but then its not a lightweight module anymore...

**Comment by uniqueg** [comment]
I don't think we need to break our necks over this. Rather than installing ZARP from here, the other way is much easier. To get there, we can first:
- Clearly document that ZARP is required and how the ZARP repo directory can be specified (#38)
- Once ZARP-cli is on Bioconda (#37), we can optionally install ZARP-cli via ZARP (e.g., via an optional `environment.cli.yml` file)

Closing this issue in favor of #38 and zavolanlab/zarp/issues/114
