### ISSUE TITLE
feat: fetch genome resources

### ISSUE THREAD

**Issue by mzavolan** [zavolanlab/zarp-cli#25]
**Is your feature request related to a problem? Please describe.**

Genome resource may not be available if SRR entries or local file paths are used as sample references, or if provided sample tables are incomplete. If the organism information is available, either because it was provided by the user or because it was inferred via HTSinfer (#34), the genome resources can be fetched from a remote resource and the sample table records updated with the local paths.

**Describe the solution you'd like**

- Use [genomepy](https://github.com/vanheeringen-lab/genomepy) to fetch FASTA & GTF resources if source/organism info is available 
- Specifically, implement the sample fetcher plugin in `zarp.plugins.sample_fetchers.genomepy`
- Triggering of the plugin should already be implemented in `zarp.zarp.process_samples()`
- Unit tests should be implemented in `tests/plugins/sample_fetchers/test_genomepy.py` (needs to be created)

**Describe alternatives you've considered**

If, for some reason or other, it turns out that `genomepy` is not suitable for our needs, we can fall back on the work in https://github.com/zavolanlab/zarp-cli/pull/28.

**Additional context**

You can have a look at [`zarp.plugins.sample_fetchers.sra`](https://github.com/zavolanlab/zarp-cli/blob/61f072d36740c89d1d66043c760f288bd3faba47/zarp/plugins/sample_fetchers/sra.py) for inspiration on how to implement the plugin.

Note that this functionality should consider the `--execution-mode`. If the value is `DRY_RUN`, resources should not be fetched. Instead, it should only be logged what _would_ happen in modes `RUN` or `PREPARE_RUN`. Check if `genomepy` has a "dry run" option.

**Comment by uniqueg** [comment]
Just a note that this functionality should consider the `--execution-mode`. If the value is `DRY_RUN`, the annotations shouldn't actually be downloaded. Instead it should be logged what _would_ be downloaded.
