### ISSUE TITLE
Use Conda for dependency management

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp-cli#36]
**Is your feature request related to a problem? Please describe.**

As a pure Python library, ZARP-cli could in principle get away with just using Pip for dependency management. However, for better compatibility with ZARP (which uses Conda), it might be helpful to migrate dependency management to Conda instead. This also makes it easier to publish ZARP-cli on Bioconda later on #37.

**Describe the solution you'd like**

Instead of `requirements.txt` and `requirements_dev.txt`, we should instead have Conda environment files, e.g., `environment.yml` and `environment.dev.yml` (just like in ZARP).

**Comment by uniqueg** [comment]
Only reason for this issue was as a preparation for #37. But turns out that isn't necessary. So closing this. More details in here: https://github.com/zavolanlab/zarp-cli/pull/39#pullrequestreview-1338188186

Apologies @fgypas

**Comment by fgypas** [comment]
No worries. It will be simpler now.
