### ISSUE TITLE
feat: genome resources management

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#5]
**Is your feature request related to a problem? Please describe.**
The issue is how to provide genome availability and compatibility with specific versions and organisms

**Describe the solution you'd like**
Implementation in `config/genome_resources.py`
The user should be able to :
   1. set default genome resources for a given organism and either 
   2. choose to always download latest ENSEMBL resources for every sample or
   3. download only missing genome resources not configured in 1. or
   4. never download any resources (app will stop if resources are not available for one or more samples)

**Additional context**
ensembl rest resources: https://rest.ensembl.org/

**Comment by mkatsanto** [comment]
https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/133

**Comment by ninsch3000** [comment]
Note that in the samples table paths to genome and annotation files have to be in the format `/path/to/ORGANISM/gene_annotations.gtf (or genome.fa)`, where `ORGANISM` has to be exactly the same as the `short_name` for library source returned by htsinfer. (Or the htsinfer short name has to be replaced in the samples table;)

**Comment by uniqueg** [comment]
This was addressed with #61
