### ISSUE TITLE
fix: use defaults from user config

### ISSUE THREAD

**Issue by balajtimate** [zavolanlab/zarp-cli#55]
**Describe the bug**
Without specificing the parameters for `--cores` and `--dependency-embedding` for the run, ZARP runs with the default parameters instead of the arguments set up at the initialization. 

**To Reproduce**

1. Initialize ZARP with `zarp --init` and cores set to some int other than 1.
2. Run ZARP _without_ specifying `--cores`.
3. Check the run configs; the `--cores` argument is set to the default of 1.
4. The same applies to `--dependency-embedding`: when initializing it with SINGULARITY, it defaults back to CONDA.

**Additional context**

**Comment by uniqueg** [comment]
The same is likely also true for `--execution-mode`
