### ISSUE TITLE
Implement initialization routine

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#6]
**Is your feature request related to a problem? Please describe.**
Upon running ZARP-cli for the first time (or whenever it is requested), users should be able to set up their own defaults, to be used for all subsequent runs, unless overridden by command-line parameters.

**Describe the solution you'd like**
An interactive session should be implemented in which a user provides defaults for the various user- and run-specific parameters. Descriptions of each parameter should be provided and a default suggested, read from a default config file shipped with ZARP-cli. Simply pressing <ENTER> for a given parameter should confirm the suggested default, otherwise the user's value is used. Values should be stored in a file `~/zarp/config.yaml`. If the file is absent, such as when ZARP-cli was first started, the initiliazation routine should be automatically triggered. Alternatively, it should be triggered if the user provides the `--init` CLI flag. Whenever ZARP-cli is executed and the user config file is present, it should be used in any run unless specifically overridden by CLI parameters.

**Comment by uniqueg** [comment]
Blocked by #1, #2, #14 & #15
