### ISSUE TITLE
Download samples from SRA

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#8]
**Is your feature request related to a problem? Please describe.**
Extension for SRA sample download compatibility

**Describe the solution you'd like**
Implementation in `extensions/sra.py`

**Additional context**
Execute only if the user inputs any SRA sample identifiers
Python package for retrieving metadata and downloading datasets from SRA/ENA:  https://pypi.org/project/pysradb/

**Comment by mkatsanto** [comment]
https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/issues/122

**Comment by mzavolan** [comment]
Tried to install and test the pysradb code. Errors all over the place. I don't think this is usable for the time being.

**Comment by mzavolan** [comment]
> Tried to install and test the pysradb code. Errors all over the place. I don't think this is usable for the time being.

Filed a bug report, the developer is aware of the issue and will try to fix it.

**Comment by dominikburri** [comment]
As discussed with @uniqueg and @mzavolan, we will write a separate Snakemake workflow for SRA downloads (using `fastq-dump`), similar to how we run HTSinfer. Will open new issues for that.

**Comment by uniqueg** [comment]
Just a note that this functionality should consider the `--execution-mode`. If the value is `DRY_RUN`, the samples shouldn't actually be downloaded. Instead it should be logged what would be downloaded.
