### ISSUE TITLE
Infer missing sample parameters with HTSinfer

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#9]
**Is your feature request related to a problem? Please describe.**
Use HTSinfer extension to fill out any missing parameters by inference.

**Describe the solution you'd like**
Implement in `extensions/htsinfer.py`
Run HTSinfer and update any of the following missing sample-specific parameters:
* organism
* read orientation
* 3’ adapter

**Comment by uniqueg** [comment]
Closing. HTSinfer will be called by ZARP itself, see zavolanlab/zarp#44
